### ISSUE TITLE
Support newer, locally-installed engines

### ISSUE THREAD

**Issue by cspotcode** [debrouwere/render#7]
Right now if I install render-cli locally into my project alongside the latest version of pug, I can't render `.pug` templates.  This is because render-cli depends directly on old versions of consolidate and all the template engines it supports.  Even if render's consolidate dependency were updated, I would still not be able to override the hardcoded engine versions from render's `package.json`.

I think render-cli should load the template engines as peer dependencies.  That way it will use whatever version of the rendering engine I've installed locally into my project, or globally for `npm install -g`.

```
npm install render-cli pug
node_modules/.bin/render input.pug
```

Or maybe there is some other way to support this?  Like a flag that causes render-cli to `require('consolidate')` relative to the parent directory? (basically forcing it to pick up the peer dependency)

**Comment by debrouwere** [comment]
The reason I included all engines out of the box was because, it turns out, if you `npm link` for local development, it won't find the global packages whereas when you just `npm install -g` it will. Not being able to link is a minor inconvenience, so I'm going to go with your approach – see the 0.3.2 release. Thanks for pointing this out.
